server:
  port: 8081

spring:
  application:
    name: cloud-storage
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/collabstack_storage}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Bluegreen18@}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:collabstack-dev-only-jwt-secret-key-please-change-in-production-min64chars}
    expiration-ms: 86400000

storage:
  nodes:
    nodes:
      - id: node-1
        host: ${NODE1_HOST:localhost}
        port: 9001
      - id: node-2
        host: ${NODE2_HOST:localhost}
        port: 9002
      - id: node-3
        host: ${NODE3_HOST:localhost}
        port: 9003
  replication:
    factor: 3
    health-check-interval-ms: 10000
    repair-interval-ms: 30000
