server:
  port: ${NODE_PORT:9001}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  node:
    id: ${NODE_ID:node-1}
    data-dir: ${DATA_DIR:./data/chunks}
